### PR TITLE
Standardize synonym type definition for PLURAL

### PR DESCRIPTION
**Pull request by cthoyt**
We're working towards standardizing synonym type definitions across the OBO Foundry. This involved getting OMO terms for several common synonym type definitions. More information in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2450.

In this PR, the ad hoc definition in ZFA for PLURAL synonyms is replaced with the standard synonym type definition OMO:0003004 for plural syonyms

CC @ybradford @cerivs

### CODE REVIEW

**Comment by cthoyt** [comment]
Emailed about this on october 31, 2023

**Comment by cthoyt** [comment]
@cerivs in f09d190 I added what I think was a missing type definition. Can you see if this fixes the editor?

**Comment by cerivs** [comment]
Looks like your pull isn't replacing  synonyms that are "RELATED PLURAL" with "RELATED OMO:0003004"

**Comment by cthoyt** [comment]
> Looks like your pull isn't replacing synonyms that are "RELATED PLURAL" with "RELATED OMO:0003004"

updated in 0c5aff7. Thanks for being patient

**Comment by cerivs** [comment]
Yay! Is working now.

**Pull request merged**
